Changes for consistency with beta release, JIRA:EB-1423
ncbi/elastic-blast-docs pull request #104
Opened 2021-12-30 17:00 UTC by tom6931

- Replaced ${YOUR_GCP_PROJECT_ID} and ${USER} in GCP quickstart config file with YOUR_GCP_PROJECT_ID and USER
- Added numbered list of needed changes to config file in both quickstarts
- Removed warning about batch length settings in both known issue pages.
- Modified machine type configuration entry to advise against specifying machine type
- Removed mem-limit from config file for "MegaBLAST on a large nucleotide set"

2022-01-03 16:55 UTC, tom6931 commented on docs/source/configuration.rst
> -    * Default: ``n1-standard-32`` for GCP, ``m5.8xlarge`` for AWS.
Added new commit that puts the default values back.

2022-01-03 20:10 UTC, boratyng approved these changes

2022-01-04 15:23 UTC, christiam requested changes

2022-01-04 15:23 UTC, christiam commented on docs/source/configuration.rst
>      * Default: ``n1-standard-32`` for GCP, ``m5.8xlarge`` for AWS.
@tom6931 , per @boratyng 's comment, it looks like the default should be:

```suggestion
    * Default: ``n1-highmem-32`` for GCP, ``m5.8xlarge`` for AWS.
```

I corroborated this in the code: https://github.com/ncbi/elastic-blast/blob/master/src/elastic_blast/constants.py#L101

2022-01-04 18:29 UTC, christiam approved these changes

2022-01-04 18:29 UTC, merged